INSERT INTO genre (id, name) VALUES
('dddddddd-dddd-dddd-dddd-dddddddddd09', 'Биография'),
('dddddddd-dddd-dddd-dddd-dddddddddd10', 'Приключения'),
('dddddddd-dddd-dddd-dddd-dddddddddd11', 'Ужасы и мистика'),
('dddddddd-dddd-dddd-dddd-dddddddddd12', 'Научпоп'),
('dddddddd-dddd-dddd-dddd-dddddddddd13', 'Психология'),
('dddddddd-dddd-dddd-dddd-dddddddddd14', 'Философия'),
('dddddddd-dddd-dddd-dddd-dddddddddd15', 'Роман'),
('dddddddd-dddd-dddd-dddd-dddddddddd16', 'Юмор и сатира');

INSERT INTO book (id, title, description, publication_year, isbn, author_name) VALUES
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee13', 'Идиот', 'Роман о князе Мышкине', 1869, '978-5-17-000013-3', 'Ф. М. Достоевский'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee14', 'Герой нашего времени', 'Роман из пяти повестей', 1840, '978-5-17-000014-4', 'М. Ю. Лермонтов'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee15', 'Отцы и дети', 'Социальный роман', 1862, '978-5-17-000015-5', 'И. С. Тургенев'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee16', 'Обломов', 'Роман о жизни помещика', 1859, '978-5-17-000016-6', 'И. А. Гончаров'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee17', 'Ревизор', 'Комедия в пяти действиях', 1836, '978-5-17-000017-7', 'Н. В. Гоголь'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee18', 'Мёртвые души', 'Поэма', 1842, '978-5-17-000018-8', 'Н. В. Гоголь'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee19', 'Доктор Живаго', 'Роман о судьбе в эпоху потрясений', 1957, '978-5-17-000019-9', 'Б. Л. Пастернак'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee20', 'Пикник на обочине', 'Научно-фантастическая повесть', 1972, '978-5-17-000020-0', 'А. и Б. Стругацкие'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee21', 'Трудно быть богом', 'Фантастический роман', 1964, '978-5-17-000021-1', 'А. и Б. Стругацкие'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee22', 'Хоббит, или Туда и обратно', 'Сказочная повесть', 1937, '978-5-17-000022-2', 'Дж. Р. Р. Толкин'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee23', 'Убийство в «Восточном экспрессе»', 'Детективный роман', 1934, '978-5-17-000023-3', 'А. Кристи'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee24', 'Десять негритят', 'Детективный роман', 1939, '978-5-17-000024-4', 'А. Кристи'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee25', 'Франкенштейн', 'Готический роман', 1818, '978-5-17-000025-5', 'М. Шелли'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee26', 'Дракула', 'Роман о вампире', 1897, '978-5-17-000026-6', 'Б. Стокер'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee27', 'Краткая история времени', 'От Большого взрыва до чёрных дыр', 1988, '978-5-17-000027-7', 'С. Хокинг'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee28', 'Думай медленно… решай быстро', 'О двух системах мышления', 2011, '978-5-17-000028-8', 'Д. Канеман'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee29', 'Так говорил Заратустра', 'Книга для всех и ни для кого', 1883, '978-5-17-000029-9', 'Ф. Ницше'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee30', 'Горе от ума', 'Комедия в стихах', 1825, '978-5-17-000030-0', 'А. С. Грибоедов'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee31', 'Вишнёвый сад', 'Пьеса', 1904, '978-5-17-000031-1', 'А. П. Чехов'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee32', 'Приключения Тома Сойера', 'Повесть о мальчике на Миссисипи', 1876, '978-5-17-000032-2', 'М. Твен'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee33', 'Робинзон Крузо', 'Роман о жизни на необитаемом острове', 1719, '978-5-17-000033-3', 'Д. Дефо'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee34', 'Жизнь Пи', 'Роман о выживании в океане', 2001, '978-5-17-000034-4', 'Я. Мартель'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee35', 'Превращение', 'Повесть', 1915, '978-5-17-000035-5', 'Ф. Кафка'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee36', 'Война миров', 'Научно-фантастический роман', 1898, '978-5-17-000036-6', 'Г. Уэллс'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee37', 'Гордость и предубеждение', 'Социальный роман', 1813, '978-5-17-000037-7', 'Дж. Остин'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee38', 'Великий Гэтсби', 'Роман о «ревущих двадцатых»', 1925, '978-5-17-000038-8', 'Ф. С. Фицджеральд'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee39', 'Унесённые ветром', 'Исторический роман', 1936, '978-5-17-000039-9', 'М. Митчелл'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee40', 'Записки из подполья', 'Повесть', 1864, '978-5-17-000040-0', 'Ф. М. Достоевский'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee41', 'Детство', 'Повесть-воспоминание', 1852, '978-5-17-000041-1', 'Л. Н. Толстой'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee42', 'Записки охотника', 'Цикл очерков', 1852, '978-5-17-000042-2', 'И. С. Тургенев');

INSERT INTO book_genre (book_id, genre_id) VALUES
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee13', 'dddddddd-dddd-dddd-dddd-dddddddddd01'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee13', 'dddddddd-dddd-dddd-dddd-dddddddddd07'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee14', 'dddddddd-dddd-dddd-dddd-dddddddddd01'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee14', 'dddddddd-dddd-dddd-dddd-dddddddddd10'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee15', 'dddddddd-dddd-dddd-dddd-dddddddddd01'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee16', 'dddddddd-dddd-dddd-dddd-dddddddddd01'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee16', 'dddddddd-dddd-dddd-dddd-dddddddddd15'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee17', 'dddddddd-dddd-dddd-dddd-dddddddddd01'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee17', 'dddddddd-dddd-dddd-dddd-dddddddddd07'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee17', 'dddddddd-dddd-dddd-dddd-dddddddddd16'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee18', 'dddddddd-dddd-dddd-dddd-dddddddddd01'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee18', 'dddddddd-dddd-dddd-dddd-dddddddddd16'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee19', 'dddddddd-dddd-dddd-dddd-dddddddddd01'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee19', 'dddddddd-dddd-dddd-dddd-dddddddddd15'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee20', 'dddddddd-dddd-dddd-dddd-dddddddddd04'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee21', 'dddddddd-dddd-dddd-dddd-dddddddddd04'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee22', 'dddddddd-dddd-dddd-dddd-dddddddddd04'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee22', 'dddddddd-dddd-dddd-dddd-dddddddddd10'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee23', 'dddddddd-dddd-dddd-dddd-dddddddddd03'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee24', 'dddddddd-dddd-dddd-dddd-dddddddddd03'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee25', 'dddddddd-dddd-dddd-dddd-dddddddddd11'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee25', 'dddddddd-dddd-dddd-dddd-dddddddddd04'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee26', 'dddddddd-dddd-dddd-dddd-dddddddddd11'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee27', 'dddddddd-dddd-dddd-dddd-dddddddddd12'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee28', 'dddddddd-dddd-dddd-dddd-dddddddddd13'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee29', 'dddddddd-dddd-dddd-dddd-dddddddddd14'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee30', 'dddddddd-dddd-dddd-dddd-dddddddddd01'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee30', 'dddddddd-dddd-dddd-dddd-dddddddddd07'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee30', 'dddddddd-dddd-dddd-dddd-dddddddddd16'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee31', 'dddddddd-dddd-dddd-dddd-dddddddddd01'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee31', 'dddddddd-dddd-dddd-dddd-dddddddddd07'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee32', 'dddddddd-dddd-dddd-dddd-dddddddddd10'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee32', 'dddddddd-dddd-dddd-dddd-dddddddddd08'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee33', 'dddddddd-dddd-dddd-dddd-dddddddddd10'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee33', 'dddddddd-dddd-dddd-dddd-dddddddddd01'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee34', 'dddddddd-dddd-dddd-dddd-dddddddddd10'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee34', 'dddddddd-dddd-dddd-dddd-dddddddddd15'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee35', 'dddddddd-dddd-dddd-dddd-dddddddddd14'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee35', 'dddddddd-dddd-dddd-dddd-dddddddddd01'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee36', 'dddddddd-dddd-dddd-dddd-dddddddddd04'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee37', 'dddddddd-dddd-dddd-dddd-dddddddddd15'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee38', 'dddddddd-dddd-dddd-dddd-dddddddddd15'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee39', 'dddddddd-dddd-dddd-dddd-dddddddddd06'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee39', 'dddddddd-dddd-dddd-dddd-dddddddddd15'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee40', 'dddddddd-dddd-dddd-dddd-dddddddddd01'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee40', 'dddddddd-dddd-dddd-dddd-dddddddddd14'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee41', 'dddddddd-dddd-dddd-dddd-dddddddddd09'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee41', 'dddddddd-dddd-dddd-dddd-dddddddddd01'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee42', 'dddddddd-dddd-dddd-dddd-dddddddddd09'),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeee42', 'dddddddd-dddd-dddd-dddd-dddddddddd01');

INSERT INTO book_copy (id, book_id, inventory_number, status) VALUES
('ffffffff-ffff-ffff-ffff-ffffffffff17', 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeee13', 'INV-017', 'AVAILABLE'),
('ffffffff-ffff-ffff-ffff-ffffffffff18', 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeee13', 'INV-018', 'AVAILABLE'),
('ffffffff-ffff-ffff-ffff-ffffffffff19', 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeee14', 'INV-019', 'AVAILABLE'),
('ffffffff-ffff-ffff-ffff-ffffffffff20', 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeee15', 'INV-020', 'AVAILABLE'),
('ffffffff-ffff-ffff-ffff-ffffffffff21', 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeee15', 'INV-021', 'AVAILABLE'),
('ffffffff-ffff-ffff-ffff-ffffffffff22', 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeee16', 'INV-022', 'AVAILABLE'),
('ffffffff-ffff-ffff-ffff-ffffffffff23', 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeee17', 'INV-023', 'AVAILABLE'),
('ffffffff-ffff-ffff-ffff-ffffffffff24', 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeee18', 'INV-024', 'AVAILABLE'),
('ffffffff-ffff-ffff-ffff-ffffffffff25', 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeee19', 'INV-025', 'AVAILABLE'),
('ffffffff-ffff-ffff-ffff-ffffffffff26', 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeee20', 'INV-026', 'AVAILABLE'),
('ffffffff-ffff-ffff-ffff-ffffffffff27', 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeee20', 'INV-027', 'AVAILABLE'),
('ffffffff-ffff-ffff-ffff-ffffffffff28', 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeee21', 'INV-028', 'AVAILABLE'),
('ffffffff-ffff-ffff-ffff-ffffffffff29', 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeee22', 'INV-029', 'AVAILABLE'),
('ffffffff-ffff-ffff-ffff-ffffffffff30', 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeee23', 'INV-030', 'AVAILABLE'),
('ffffffff-ffff-ffff-ffff-ffffffffff31', 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeee24', 'INV-031', 'AVAILABLE'),
('ffffffff-ffff-ffff-ffff-ffffffffff32', 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeee25', 'INV-032', 'AVAILABLE'),
('ffffffff-ffff-ffff-ffff-ffffffffff33', 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeee26', 'INV-033', 'AVAILABLE'),
('ffffffff-ffff-ffff-ffff-ffffffffff34', 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeee27', 'INV-034', 'AVAILABLE'),
('ffffffff-ffff-ffff-ffff-ffffffffff35', 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeee28', 'INV-035', 'AVAILABLE'),
('ffffffff-ffff-ffff-ffff-ffffffffff36', 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeee29', 'INV-036', 'AVAILABLE'),
('ffffffff-ffff-ffff-ffff-ffffffffff37', 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeee30', 'INV-037', 'AVAILABLE'),
('ffffffff-ffff-ffff-ffff-ffffffffff38', 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeee31', 'INV-038', 'AVAILABLE'),
('ffffffff-ffff-ffff-ffff-ffffffffff39', 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeee32', 'INV-039', 'AVAILABLE'),
('ffffffff-ffff-ffff-ffff-ffffffffff40', 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeee33', 'INV-040', 'AVAILABLE'),
('ffffffff-ffff-ffff-ffff-ffffffffff41', 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeee34', 'INV-041', 'AVAILABLE'),
('ffffffff-ffff-ffff-ffff-ffffffffff42', 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeee35', 'INV-042', 'AVAILABLE'),
('ffffffff-ffff-ffff-ffff-ffffffffff43', 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeee36', 'INV-043', 'AVAILABLE'),
('ffffffff-ffff-ffff-ffff-ffffffffff44', 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeee37', 'INV-044', 'AVAILABLE'),
('ffffffff-ffff-ffff-ffff-ffffffffff45', 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeee37', 'INV-045', 'AVAILABLE'),
('ffffffff-ffff-ffff-ffff-ffffffffff46', 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeee38', 'INV-046', 'AVAILABLE'),
('ffffffff-ffff-ffff-ffff-ffffffffff47', 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeee39', 'INV-047', 'AVAILABLE'),
('ffffffff-ffff-ffff-ffff-ffffffffff48', 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeee40', 'INV-048', 'AVAILABLE'),
('ffffffff-ffff-ffff-ffff-ffffffffff49', 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeee41', 'INV-049', 'AVAILABLE'),
('ffffffff-ffff-ffff-ffff-ffffffffff50', 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeee42', 'INV-050', 'AVAILABLE');